apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  labels:
    operator.tekton.dev/release: "v0.71.0"
    version: "v0.71.0"
  name: "tektonconfigs.operator.tekton.dev"
spec:
  group: "operator.tekton.dev"
  names:
    kind: "TektonConfig"
    listKind: "TektonConfigList"
    plural: "tektonconfigs"
    singular: "tektonconfig"
  preserveUnknownFields: false
  scope: "Cluster"
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".status.version"
          name: "Version"
          type: "string"
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
          name: "Ready"
          type: "string"
        - jsonPath: ".status.conditions[?(@.type==\"Ready\")].message"
          name: "Reason"
          type: "string"
      name: "v1alpha1"
      schema:
        openAPIV3Schema:
          description: "Schema for the tektonconfigs API"
          type: "object"
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
