apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: "v0.16.2"
  name: "routes.apigatewayv2.services.k8s.aws"
spec:
  group: "apigatewayv2.services.k8s.aws"
  names:
    kind: "Route"
    listKind: "RouteList"
    plural: "routes"
    singular: "route"
  scope: "Namespaced"
  versions:
    - name: "v1alpha1"
      schema:
        openAPIV3Schema:
          description: "Route is the Schema for the Routes API"
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: "string"
            kind:
              description: "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: "string"
            metadata:
              type: "object"
            spec:
              description: "RouteSpec defines the desired state of Route.\n\nRepresents a route."
              properties:
                apiID:
                  description: "The API identifier."
                  type: "string"
                apiKeyRequired:
                  description: "Specifies whether an API key is required for the route. Supported only for\nWebSocket APIs."
                  type: "boolean"
                apiRef:
                  description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference\ntype to provide more user friendly syntax for references using 'from' field\nEx:\nAPIIDRef:\n\n\tfrom:\n\t  name: my-api"
                  properties:
                    from:
                      description: "AWSResourceReference provides all the values necessary to reference another\nk8s resource for finding the identifier(Id/ARN/Name)"
                      properties:
                        name:
                          type: "string"
                        namespace:
                          type: "string"
                      type: "object"
                  type: "object"
                authorizationScopes:
                  description: "The authorization scopes supported by this route."
                  items:
                    type: "string"
                  type: "array"
                authorizationType:
                  description: "The authorization type for the route. For WebSocket APIs, valid values are\nNONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for\nusing a Lambda authorizer For HTTP APIs, valid values are NONE for open access,\nJWT for using JSON Web Tokens, AWS_IAM for using AWS IAM permissions, and\nCUSTOM for using a Lambda authorizer."
                  type: "string"
                authorizerID:
                  description: "The identifier of the Authorizer resource to be associated with this route.\nThe authorizer identifier is generated by API Gateway when you created the\nauthorizer."
                  type: "string"
                authorizerRef:
                  description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference\ntype to provide more user friendly syntax for references using 'from' field\nEx:\nAPIIDRef:\n\n\tfrom:\n\t  name: my-api"
                  properties:
                    from:
                      description: "AWSResourceReference provides all the values necessary to reference another\nk8s resource for finding the identifier(Id/ARN/Name)"
                      properties:
                        name:
                          type: "string"
                        namespace:
                          type: "string"
                      type: "object"
                  type: "object"
                modelSelectionExpression:
                  description: "The model selection expression for the route. Supported only for WebSocket\nAPIs."
                  type: "string"
                operationName:
                  description: "The operation name for the route."
                  type: "string"
                requestModels:
                  additionalProperties:
                    type: "string"
                  description: "The request models for the route. Supported only for WebSocket APIs."
                  type: "object"
                requestParameters:
                  additionalProperties:
                    description: "Validation constraints imposed on parameters of a request (path, query string,\nheaders)."
                    properties:
                      required:
                        type: "boolean"
                    type: "object"
                  description: "The request parameters for the route. Supported only for WebSocket APIs."
                  type: "object"
                routeKey:
                  description: "The route key for the route."
                  type: "string"
                routeResponseSelectionExpression:
                  description: "The route response selection expression for the route. Supported only for\nWebSocket APIs."
                  type: "string"
                target:
                  description: "The target for the route."
                  type: "string"
                targetRef:
                  description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference\ntype to provide more user friendly syntax for references using 'from' field\nEx:\nAPIIDRef:\n\n\tfrom:\n\t  name: my-api"
                  properties:
                    from:
                      description: "AWSResourceReference provides all the values necessary to reference another\nk8s resource for finding the identifier(Id/ARN/Name)"
                      properties:
                        name:
                          type: "string"
                        namespace:
                          type: "string"
                      type: "object"
                  type: "object"
              required:
                - "routeKey"
              type: "object"
            status:
              description: "RouteStatus defines the observed state of Route"
              properties:
                ackResourceMetadata:
                  description: "All CRs managed by ACK have a common `Status.ACKResourceMetadata` member\nthat is used to contain resource sync state, account ownership,\nconstructed ARN for the resource"
                  properties:
                    arn:
                      description: "ARN is the Amazon Resource Name for the resource. This is a\nglobally-unique identifier and is set only by the ACK service controller\nonce the controller has orchestrated the creation of the resource OR\nwhen it has verified that an \"adopted\" resource (a resource where the\nARN annotation was set by the Kubernetes user on the CR) exists and\nmatches the supplied CR's Spec field values.\nhttps://github.com/aws/aws-controllers-k8s/issues/270"
                      type: "string"
                    ownerAccountID:
                      description: "OwnerAccountID is the AWS Account ID of the account that owns the\nbackend AWS service API resource."
                      type: "string"
                    region:
                      description: "Region is the AWS region in which the resource exists or will exist."
                      type: "string"
                  required:
                    - "ownerAccountID"
                    - "region"
                  type: "object"
                apiGatewayManaged:
                  description: "Specifies whether a route is managed by API Gateway. If you created an API\nusing quick create, the $default route is managed by API Gateway. You can't\nmodify the $default route key."
                  type: "boolean"
                conditions:
                  description: "All CRs managed by ACK have a common `Status.Conditions` member that\ncontains a collection of `ackv1alpha1.Condition` objects that describe\nthe various terminal states of the CR and its backend AWS service API\nresource"
                  items:
                    description: "Condition is the common struct used by all CRDs managed by ACK service\ncontrollers to indicate terminal states  of the CR and its backend AWS\nservice API resource"
                    properties:
                      lastTransitionTime:
                        description: "Last time the condition transitioned from one status to another."
                        format: "date-time"
                        type: "string"
                      message:
                        description: "A human readable message indicating details about the transition."
                        type: "string"
                      reason:
                        description: "The reason for the condition's last transition."
                        type: "string"
                      status:
                        description: "Status of the condition, one of True, False, Unknown."
                        type: "string"
                      type:
                        description: "Type is the type of the Condition"
                        type: "string"
                    required:
                      - "status"
                      - "type"
                    type: "object"
                  type: "array"
                routeID:
                  description: "The route ID."
                  type: "string"
              type: "object"
          type: "object"
      served: true
      storage: true
      subresources:
        status: {}
